// Copyright (c) Microsoft. All rights reserved.

import { makeStyles } from '@fluentui/react-components';
import React, { AnchorHTMLAttributes, ClassAttributes } from 'react';
import ReactMarkdown, { ExtraProps } from 'react-markdown';
import rehypeMathjax from 'rehype-mathjax';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import remarkSupersub from 'remark-supersub';
import { IChatMessage } from '../../../libs/models/ChatMessage';
import * as utils from './../../utils/TextUtils';
const useClasses = makeStyles({
    content: {
        wordBreak: 'break-word',
    },
});

interface ChatHistoryTextContentProps {
    message: IChatMessage;
}

export const ChatHistoryTextContent: React.FC<ChatHistoryTextContentProps> = ({ message }) => {
    const classes = useClasses();
    const content = utils.escapeMarkdownLinks(
        utils.replaceMathBracketsWithDollarSigns(
            utils.replaceBracketStyleCitationsWithCaret(
                utils.replaceCitationLinksWithIndices(utils.formatChatTextContent(message.content), message),
            ),
        ),
    );

    // Necessary for ensuring that a tags generated by the ReactMarkdown component will open links in a new tab rather than redirecting the current page.
    const NewTabLinkRenderer = (
        props: ClassAttributes<HTMLAnchorElement> & AnchorHTMLAttributes<HTMLAnchorElement> & ExtraProps,
    ) => {
        return (
            <a href={props.href} target={'_blank'} rel="noreferrer">
                {props.children}
            </a>
        );
    };

    return (
        <div className={classes.content}>
            <ReactMarkdown
                components={{ a: NewTabLinkRenderer }}
                rehypePlugins={[rehypeMathjax]}
                remarkPlugins={[remarkGfm, remarkSupersub, remarkMath]}
            >
                {content}
            </ReactMarkdown>
        </div>
    );
};
