<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CopilotChat.Shared</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Vision.ImageAnalysis" Version="1.0.0" />
    <PackageReference Include="Microsoft.KernelMemory" Version="0.97.250211.1" />
    <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.97.250211.1" />
    <PackageReference Include="Microsoft.KernelMemory.MemoryDb.Postgres" Version="0.97.250211.1" />
    <PackageReference Include="Microsoft.KernelMemory.MemoryDb.Redis" Version="0.98.250323.1" />
    <PackageReference Include="Microsoft.KernelMemory.Orchestration.RabbitMQ" Version="0.97.250211.1" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

</Project>
