cert:
  hosts:
    - host: test.q-pilot.quartech.com
    - host: test.api.q-pilot.quartech.com

image:
  tag: "test"

secretProviderClass:
  # Retrieved from Terraform Output
  vaultName: "kvt-copilot-cnc-app-test"

###############
# FE Common values
###############

fe:
  env:
    - name: "VITE_APP_BACKEND_URI"
      value: "https://test.api.q-pilot.quartech.com"
    - name: "VITE_APP_ENVIRONMENT"
      value: "test"

###############
# BE Common values
###############

be:
  env:
    - name: "ASPNETCORE_URLS"
      value: "http://+:8080"
    - name: "ASPNETCORE_ENVIRONMENT"
      value: "Test"
    - name: "AZURE_TENANT_ID"
      value: "898fdc18-1bd2-4a3b-84a7-2efb988e3b90"
    - name: "AZURE_CLIENT_ID"
      value: "69a849fa-1e3f-46c3-8616-1cbc060ece11"

###############
# webapp specific values
###############

webapp:
  image:
    tag: "test"
  ingress:
    hosts:
      - host: test.q-pilot.quartech.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - test.q-pilot.quartech.com

###############
# webapi specific values
###############

webapi:
  image:
    tag: "test"

  volumeMounts:
    - name: appsettings-volume
      mountPath: /app/appsettings.json
      subPath: appsettings.json
    - name: appsettings-test-volume
      mountPath: /app/appsettings.Test.json
      subPath: appsettings.Test.json
    - name: secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true

  volumes:
    - name: appsettings-volume
      configMap:
        name: q-pilot-webapi
        items:
          - key: appsettings.json
            path: appsettings.json
    - name: appsettings-test-volume
      configMap:
        name: q-pilot-webapi
        items:
          - key: appsettings.Test.json
            path: appsettings.Test.json
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "q-pilot-webapi"

  configs:
    - config/test/appsettings.json
    - config/test/appsettings.Test.json

  ingress:
    hosts:
      - host: test.api.q-pilot.quartech.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - test.api.q-pilot.quartech.com
