name: Build Images
# This workflow builds Docker images for the application and pushes them to Azure Container Registry (ACR).
# It is triggered on demand or can be called from another workflow.
# The workflow builds images for the webapi and webapp components of the application.
# The workflow uses a matrix strategy to build multiple images in parallel.
# The workflow uses the Docker Buildx action to build and push the images to ACR.
# The workflow also uses the Docker Metadata action to extract metadata for the images, such as tags and labels.
# The workflow uses the Docker Login action to authenticate with ACR before building and pushing the images.

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-and-push-image:
    name: Build and push images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - file: ./docker/webapi/Dockerfile
            image: chat-copilot-webapi
            build-args: |

          # Only build nginx image
          # - file: ./docker/webapp/Dockerfile
          #   image: ${{ github.event.repository.name }}-webapp
          #   build-args: |

          - file: ./docker/webapp/Dockerfile.nginx
            image: chat-copilot-webapp
            build-args: |

          # Excluded for now
          # - file: ./docker/plugins/web-searcher/Dockerfile
          #   image: ${{ github.event.repository.name }}-web-searcher
          #   build-args: |

          # Excluded for now
          # - file: ./docker/memorypipeline/Dockerfile
          #   image: ${{ github.event.repository.name }}-memorypipeline
          #   build-args: |

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY }}/${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.build-args }}
